### ISSUE TITLE
v5.0.1: composer.json is missing wallee/sdk dependency

### ISSUE THREAD

**Issue by darinda** [wallee-payment/shopware-6#8]
Hi there,

the version 5.0.1 of the module currently [does not require](https://github.com/wallee-payment/shopware-6/blob/5.0.1/composer.json#L55) the wallee/sdk package (while [5.0.0 does](https://github.com/wallee-payment/shopware-6/blob/5.0.0/composer.json#L62)). This makes v5.0.1 of the plugin non-functional.

```
{
    "errors": [
        {
            "code": "0",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "Attempted to load class \u0022TransactionState\u0022 from namespace \u0022Wallee\\Sdk\\Model\u0022.\nDid you forget a \u0022use\u0022 statement for another namespace?"
        }
    ]
}
```

Looks like this requirement was simply forgotten? Manually `composer require`ing the wallee/sdk packages fixes the problem.

**Comment by theodorspringwallee** [comment]
Dear [darinda](https://github.com/darinda)

Are you still using Shopware 6.4?

That might be the reason, because on this repository we did the switch to be only compatible with Shopware 6.5 (made in v5.0.0)

In case you are using SW 6.4, please use the following repository: https://github.com/wallee-payment/shopware-6-4
(as mentioned in the readme)

If you are using Shopware 6.5 with this repository, we can investigate this.

Many thanks for your answer.

Best regards

**Comment by darinda** [comment]
Dear @theodorspringwallee ,

the used shopware version is v6.5.4.1 - which shouldn't play any role, though. Please see my original comment to note that v5.0.0 of the module has the correct requirements while v5.0.1 does not. 

regards
René

**Comment by theodorspringwallee** [comment]
Dear [darinda](https://github.com/darinda)

According to our developers, this mentioned change in v5.0.1 was reverted in v5.0.2.

So please can you install the [wallee plugin v5.0.2](https://github.com/wallee-payment/shopware-6/releases/tag/5.0.2) to see, if this solves your issue?

Many thanks.

Best regards

**Comment by darinda** [comment]
Dear @theodorspringwallee ,

thanks, 5.0.2 works fine.

regards

**Comment by theodorspringwallee** [comment]
Dear [darinda](https://github.com/darinda)

Great to hear.

Ok, then we will close this git issue.

Best regards
